FORMAT: 1A
HOST: twistory.pythonanywhere.com/

#### Twistory


**Version: v1**

Resources

+ [State](<http://idb14.apiary-mock.com/states)
+ [Park](<http://idb14.apiary-mock.com/parks)
+ [Hike](<http://idb14.apiary-mock.com/hikes)


# Group States


## State Collection [/states.json]
+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/states.json>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
         "name": "Utah", "flag": "link to pic of flag" 
         }, 
         {
         "name": "Texas", "flag": "link to pic of flag"
         },
         {
         "name": "California", "flag: "link to pic of flag"
         }]
        ```
        
### List the name and id of all states [GET]
+ Response 200

    [State Collection][]



## State [/states/state_name.json]

+ Parameters
    + state_name (required, string, `GET /states/Texas.json`) 
    
+ Model (application/json)
    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/states/Utah.json>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "name": "Utah", "date_founded": "1/4/1896", "population": "29000872",
                   "size": "84899", "video": "link to video"
            "parks": [{"name": "Zion", "page": "/parks/1"}],
         }
        ```
      

### List all info of the state with the given id [GET]

+ Response 200 (application/json)

    [State][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }



# Group Parks

## Park Collection [/parks.json]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/parks.json>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
         "name": "Zion", "pic": "link to picture of park" 
        }, {
         "name": "Yosemite", "pic": "link to picture of park" 
        }, {
         "name": "Denail", "pic": "link to picture of park"
        }]
        ```

### List the id and name of all parks [GET]

+ Response 200 (application/json)

    [Park Collection][]


## Park [/parks/park_id.json]

+ Parameters
    + park_id (required, string,`GET /parks/Grand Cayon.json`) ...

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/parks/Yosemite.json>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "name": "Yosemite", "size": "747956 acres",
            "elevation": "13114 ft", "visitors": "100000 per year",
            "state": "California        
        }
        ```

### List all info of the park with the given id [GET]

+ Response 200 (application/json)

    [Park][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }


# Group Hikes

## Hike Collection [/hikes.json]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/hikes.json>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
            "name": "Mirror Lake Loop", "pic": "link to picture of the hike"
         },
         {
            "name": "Hallet Peak", "pic": "link to picture of the hike"
        }]
        ```



### List the id and name of all hikes [GET]

+ Response 200 (application/json)

    [Hike Collection][]

## Hike [/hikes/hike_id.json]

+ Parameters
    + hike_id (required, string, `GET /hike/Mirror Lake Loop.json`)

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/hikes/Mirror Lake Loop.json>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "id": 1, "name": "Mirror Lake Loop", "Distance": "5 miles",
            "estimated_time": "90 min", "difficulty": "moderate", "pic": "link to pic"
            "park": "Yosemite"          
        } 
        ```


### List all info of the hike with the given id [GET]

+ Response 200 (application/json)

    [Hike][]   
    

+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }
        