FORMAT: 1A
HOST: twistory.pythonanywhere.com/

#### Twistory


**Version: v1**

Resources

+ [State](<http://idb14.apiary-mock.com/states)
+ [Park](<http://idb14.apiary-mock.com/parks)
+ [Hike](<http://idb14.apiary-mock.com/hikes)


# Group States


## State Collection [/states]
+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/handles>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
         "id": 1, "name": "Utah", 
         }, 
         {
         "id": 2, "name": "Texas",
         },
         {
         "id": 3, "name": "California", 
         }]
        ```
        
### List the name and id of all states [GET]
+ Response 200

    [State Collection][]



## State [/states/state_id]

+ Parameters
    + state_id (required, integer, `GET /states/234`) ... the id given to a state by this website
    
+ Model (application/json)
    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/states/1>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "id": 1, "name": "Utah", "date_founded": "1/4/1896", "population": "29000872",
                   "size(mile^2)": "84899",
            "parks": [{"id":1, "name": "Zion", "page": "/parks/1"}],
         }
        ```
      

### List all info of the state with the given id [GET]

+ Response 200 (application/json)

    [State][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }



# Group Parks

## Park Collection [/parks]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/parks>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
         "id": 1, "name": "Zion" 
        }, {
         "id": 2, "name": "Yosemite" 
        }, {
         "id": 3, "name": "Denail"
        }]
        ```

### List the id and name of all parks [GET]

+ Response 200 (application/json)

    [Park Collection][]


## Park [/parks/park_id]

+ Parameters
    + park_id (required, integer,`GET /parks/45454`) ... the id given to a park by this website

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/parks/2>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "id": 2, "name": "Yosemite", "size(acres)": "747956",
            "elevation(ft)": "13114",
            "in_state": [{"id":3, "name": "California", "page": "/states/3"}],           
            "hikes": [{"id":1, "name":"Mirror Lake Loop", "page": "/hikes/1"}]
        }
        ```

### List all info of the park with the given id [GET]

+ Response 200 (application/json)

    [Park][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }


# Group Hikes
Clusters are groups that are associated with multiple handles and hashtags

## Hike Collection [/hikes]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/hikes>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
            "id": 1, "name": "Mirror Lake Loop"
         },
         {
            "id": 2, "name": "Hallet Peak"
        }]
        ```



### List the id and name of all hikes [GET]

+ Response 200 (application/json)

    [Hike Collection][]

## Hike [/hikes/hike_id]

+ Parameters
    + hike_id (required, integer, `GET /hike/2`) ... the id given to a hike by this website

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/hikes/1>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "id": 1, "name": "Mirror Lake Loop", "Distance(mile)": "5",
            "estimated_time(min)": "90", "difficulty": "moderate", 
            "in_park": {"id": 2, "name": "Yosemite", "page": "/parks/2"}          
        } 
        ```


### List all info of the hike with the given id [GET]

+ Response 200 (application/json)

    [Hike][]   
    

+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }
        